### ISSUE TITLE
Problems when you "Alt-Click" the Rapier recipe in quickbuy

### ISSUE THREAD

**Issue by XAgent1990** [AngelArenaAllstars/Bug-Reports#18]
**Date:** June 04 2017
**Reported By:** XAgent
**Is it reproducible:** **_Yes_** / Occasionally / No

## Description
There are three major problems:
1. The game temporarily freezes when you do this for the first time.
2. It is called "UNKNOWN" in the chat and not "Devine Rapier Recipe"
3. You can not purchase it. Ever.

## Steps to Produce/Reproduce
Just start a new game and put only the recipe of Devine Rapier into the quickbuy and Alt-Click it.

## Expected Results
1. It should from the first time just instantly show how much more gold you need.
2. It should be called Devine Rapier Recipe in the chat.
3. It should be purchasable when you have 150.000 gold

## Actual Results
1. The game freezes for about 5-10 seconds, nearly looking to crash.
2. It is called "UNKNOWN"
3. It will say the right amount while you have <=50,000 gold. after that it will always say you need 100,000 more gold.

## Possible workarounds
I sadly do not know what can cause this thus can not tell how to fix this.

## Attachments / documentation.
![grafik](https://cloud.githubusercontent.com/assets/12500926/26762899/55fd5436-494a-11e7-9995-7abea9651869.png)
![grafik](https://cloud.githubusercontent.com/assets/12500926/26762910/78e0ab4c-494a-11e7-92f7-584db9a75867.png)

## Other Information
No more information given.

**Comment by Haganeko** [comment]
Not being able to buy it is intentional, as of now, since the shop can't handle costs greater than 50k gold.
