### ISSUE TITLE
Solar crest and heart transplant are not compatible 

### ISSUE THREAD

**Issue by 101necro** [AngelArenaAllstars/Bug-Reports#20]
Solar crest and heart transplant have the same cooldowns meaning that only one can be used at one time.

**Comment by XAgent1990** [comment]
I think you are supposed to only use one way of solar crest, either keep upgrading it or going for heart.
Other problem though is that a unit you affect with transplant will lose its effect if solar crest is used as well.

**Comment by 101necro** [comment]
Oh okay thank you
