### ISSUE TITLE
Dissasamble Greater Arcane Boots lvl 1, then Farming Core is locked and cant be unlocked

### ISSUE THREAD

**Issue by Darksold** [AngelArenaAllstars/Bug-Reports#23]
If you use the Farming Core to upgrade Arcane Boots to Greater Arcane Boots and you disassamble them again the Farming Core switches to Lock Combining, then you can't right click on it so you can't Unlock Combining.

**Comment by Trildar** [comment]
Was fixed. Now Greater Arcanes can't be disassembled anyway.
