### ISSUE TITLE
"Farming Core becomes locked and unusable when Greater Arcane Boots are dissasembled

### ISSUE THREAD

**Issue by ValkyGr** [AngelArenaAllstars/Bug-Reports#36]
Today while playing a game with tidehunter i bought greater arcane boots and then wanted to dissasemble them to buy greater guardian graves. When i dissasembled my arcane boots, my farming core got locked for combining and became unusable and as you cant right click on cores i was unable to unlock combining. Tried disconnectiong and reconnecting to see if it would fix the issues but my core was still locked. 
The bug can be reproduced as i tried reproducing it in a solo lobby with cheats enabled to quicky cheat in a few farming cores.

**Comment by ProstoSanja** [comment]
Probably fixed

**Comment by Trildar** [comment]
Duplicate of #23.
