### ISSUE TITLE
Arc Warden Double + Greater Arcane

### ISSUE THREAD

**Issue by DeiRex75** [AngelArenaAllstars/Bug-Reports#39]
If Arc Warden has Greater Arcane Boots and uses Tempest Double, it seems to be that his Illusion's boots give money towards the real one.

**Steps to Produce/Reproduce**
1. Buy Greater Arcane Boots
2. Watch Gold
3. Use Tempest Double
4. See increased Gold income

**Expected Results**
The same money income without Tempest Dobuel.

**Actual Results**
Doubled money income of arcane boots.

**Comment by Trildar** [comment]
Effectively the same as #73. Fixed in the same commit.
