### ISSUE TITLE
Troll Warlord + Greater Phase bOots

### ISSUE THREAD

**Issue by warpdragon** [AngelArenaAllstars/Bug-Reports#42]
If Troll warlord gets greater phase boots he can't stack up his fervor on creeps anymore (the split shot makes it reset as if he hits a new unit every time)

this isn't a huge deal but it's a quality of life for players so we might want to look into it soon

**Comment by Trildar** [comment]
Possibly fixed by Greater Phase Boots no longer proccing attack modifiers. Need confirmation.
