### ISSUE TITLE
Picking Random Hero: Crash

### ISSUE THREAD

**Issue by warpdragon** [AngelArenaAllstars/Bug-Reports#47]
I picked a random hero 4 times and i crashed all of the times.
I dont know if its a patch bug, game bug or just my PC and i culdnt reconnect to the game either.

(Sorry if i spell anything wrong i live in Sweden.)

Chrono
>>Do you have the console output or a recording of the game? (Don't worry about spelling)

**Comment by ProstoSanja** [comment]
Tested five times, also tried to run out of time and so on. Can't reproduce
