### ISSUE TITLE
Game Breaker: Cores/Kills/Cave and more breaking

### ISSUE THREAD

**Issue by Ponnyn** [AngelArenaAllstars/Bug-Reports#69]
Sometimes, some games just break. it most often happens after a duel (the duel dose not end). After that cores wont drop, the cave breaks, Kills are not getting counted and people cant respawn if they die to anything else then an enemy hero.

**Comment by The-Otter** [comment]
I had the same issue although I thought it was just due to it being the "short game" option, was yours a normal game?

**Comment by The-Otter** [comment]
I had the same issue although I thought it was just due to it being the "short game" option, was yours a normal game?

**Comment by Ponnyn** [comment]
Iw had it happen a lote of games... and i am even at this point trying to find what triggers the break so i can report it. (it happens in short, long and normal.)

**Comment by imaGecko** [comment]
Do you have any specific observations on what happened before the game broke?

**Comment by Ponnyn** [comment]
No.. :( sorry. as i said im trying to figure out what the trigger is... (what is causing it)

**Comment by Haganeko** [comment]
This is generally a sign that zonecontrol is breaking. Logs might be useful.

**Comment by Ponnyn** [comment]
Yeah im on it <3 (trying to find/trigger it again with the vconsole in the backgrund)

**Comment by Ponnyn** [comment]
[ W ResourceSystem ]: Error loading resource file "soundevents/soundevents_test.vsndevts_c" (Error: ERROR_FILEOPEN)
[ W PanoramaScript ]: !! (s2r://panorama/scripts/custom_game/game_info.vjs_c, line:7, col:59) - TypeError: Cannot read property 'GetParent' of null
[ W ResourceSystem ]: Error loading resource file "particles/rain_fx/econ_weather_aurora_j.vpcf_c" (Error: ERROR_FILEOPEN)
[ W General        ]: PNG load error Incorrect bKGD chunk length
[ W PanoramaScript ]: !! (s2r://panorama/scripts/custom_game/health_mana.vjs_c, line:33, col:43) - TypeError: Cannot read property 'HealthRegen' of undefined
[ W General        ]: ERROR: CParticleSnapshot::Unserialize - could not load file 0!
[ W General        ]: ERROR: CParticleSnapshot::Unserialize - could not load file  particles/models/particle/square_trace_40_points_fx.psf!
[ W ResourceSystem ]: Error loading resource file "panorama/images/heroes/npc_dota_neutral_kobold_tunneler_png.vtex_c" (Error: ERROR_FILEOPEN)
[ W ResourceSystem ]: Error loading resource file "panorama/images/heroes/npc_dota_neutral_beardude_png.vtex_c" (Error: ERROR_FILEOPEN)
[ W VScript        ]: Script Runtime Error: ...pk:scripts\vscripts\modifiers\modifier_generic_bonus.lua:28: attempt to index local 'ability' (a nil value)
[ W VScript        ]: Script Runtime Error: ...:scripts\vscripts\items\farming\greater_travel_boots.lua:149: attempt to index a nil value
[ W VScript        ]: Script Runtime Error: ...:scripts\vscripts\items\farming\greater_travel_boots.lua:149: attempt to index a nil value
[ W VScript        ]: Script Runtime Error: ...:scripts\vscripts\items\farming\greater_travel_boots.lua:149: attempt to index a nil value
[ W ResourceSystem ]: Error loading resource file "panorama/layout/custom_game/need_greed_pass/panel.vxml_c" (Error: ERROR_FILEOPEN)
[ W ResourceSystem ]: Error loading resource file "panorama/layout/custom_game/need_greed_pass/panel.vxml_c" (Error: ERROR_FILEOPEN)
[ W ResourceSystem ]: Error loading resource file "panorama/layout/custom_game/need_greed_pass/panel.vxml_c" (Error: ERROR_FILEOPEN)
[ W ResourceSystem ]: Error loading resource file "panorama/layout/custom_game/need_greed_pass/panel.vxml_c" (Error: ERROR_FILEOPEN)
[ W ResourceSystem ]: Error loading resource file "panorama/layout/custom_game/need_greed_pass/panel.vxml_c" (Error: ERROR_FILEOPEN)
[ W ResourceSystem ]: Error loading resource file "panorama/layout/custom_game/need_greed_pass/panel.vxml_c" (Error: ERROR_FILEOPEN)
[ W ResourceSystem ]: Error loading resource file "panorama/layout/custom_game/need_greed_pass/panel.vxml_c" (Error: ERROR_FILEOPEN)
[ W ResourceSystem ]: Error loading resource file "panorama/layout/custom_game/need_greed_pass/panel.vxml_c" (Error: ERROR_FILEOPEN)
[ W ResourceSystem ]: Error loading resource file "panorama/layout/custom_game/need_greed_pass/panel.vxml_c" (Error: ERROR_FILEOPEN)
[ W VScript        ]: Script Runtime Error: ...:scripts\vscripts\items\farming\greater_travel_boots.lua:149: attempt to index a nil value
[ W VScript        ]: Script Runtime Error: ...:scripts\vscripts\items\farming\greater_travel_boots.lua:149: attempt to index a nil value
[ W ResourceSystem ]: Error loading resource file "panorama/images/heroes/npc_dota_neutral_custom_big_pupper_png.vtex_c" (Error: ERROR_FILEOPEN)
[ W ResourceSystem ]: Error loading resource file "panorama/layout/custom_game/need_greed_pass/panel.vxml_c" (Error: ERROR_FILEOPEN)
[ W ResourceSystem ]: Error loading resource file "panorama/layout/custom_game/need_greed_pass/panel.vxml_c" (Error: ERROR_FILEOPEN)
[ W ResourceSystem ]: Error loading resource file "panorama/images/heroes/npc_dota_boss_tier_3_png.vtex_c" (Error: ERROR_FILEOPEN)
[ W ResourceSystem ]: Error loading resource file "panorama/images/heroes/npc_dota_boss_tier_4_png.vtex_c" (Error: ERROR_FILEOPEN)
[ W ResourceSystem ]: Error loading resource file "panorama/layout/custom_game/need_greed_pass/panel.vxml_c" (Error: ERROR_FILEOPEN)
[ W ResourceSystem ]: Error loading resource file "materials/vgui/hud/minimap_purple.vmat_c" (Error: ERROR_FILEOPEN)
[ W ResourceSystem ]: Error loading resource file "materials/vgui/hud/minimap_cyan.vmat_c" (Error: ERROR_FILEOPEN)
[ W ResourceSystem ]: Error loading resource file "materials/vgui/hud/minimap_green.vmat_c" (Error: ERROR_FILEOPEN)
[ W ResourceSystem ]: Error loading resource file "materials/vgui/hud/minimap_red.vmat_c" (Error: ERROR_FILEOPEN)
[ W ResourceSystem ]: Error loading resource file "materials/vgui/hud/minimap_gold.vmat_c" (Error: ERROR_FILEOPEN)
[ W ResourceSystem ]: Error loading resource file "materials/vgui/hud/minimap_white.vmat_c" (Error: ERROR_FILEOPEN)
[ W PanoramaScript ]: !! (s2r://panorama/scripts/custom_game/game_info.vjs_c, line:7, col:59) - TypeError: Cannot read property 'GetParent' of null
[ W ResourceSystem ]: Error loading resource file "particles/rain_fx/econ_weather_aurora_j.vpcf_c" (Error: ERROR_FILEOPEN)
[ W General        ]: PNG load error Incorrect bKGD chunk length
[ W PanoramaScript ]: !! (s2r://panorama/scripts/custom_game/health_mana.vjs_c, line:33, col:43) - TypeError: Cannot read property 'HealthRegen' of undefined
[ W ResourceSystem ]: Error loading resource file "models/heroes/keeper_of_the_light/horsefx.vmdl_c" (Error: ERROR_FILEOPEN)

**Comment by Ponnyn** [comment]
All the errors for one game that broke ^

**Comment by Ponnyn** [comment]
So the game breaker is back and this is what i have found do far.

**Comment by Ponnyn** [comment]
[ W General        ]: Datadesc import error: Field "m_flIntensity" in the datadesc for class "C_EnvDeferredLight" has not been schematized!
[ W General        ]: Datadesc import error: Field "m_flLightSize" in the datadesc for class "C_EnvDeferredLight" has not been schematized!
[ W General        ]: Datadesc import error: Field "m_flLightSize" in the datadesc for class "C_EnvDeferredLight" has not been schematized!
[ W General        ]: Datadesc import error: Field "m_flSpotFoV" in the datadesc for class "C_EnvDeferredLight" has not been schematized!
[ W General        ]: Datadesc import error: Field "m_flStartFalloff" in the datadesc for class "C_EnvDeferredLight" has not been schematized!
[ W General        ]: Datadesc import error: Field "m_flDistanceFalloff" in the datadesc for class "C_EnvDeferredLight" has not been schematized!
[ W General        ]: Datadesc import error: Field "m_nFlags" in the datadesc for class "C_EnvDeferredLight" has not been schematized!
[ W ResourceSystem ]: Error loading resource file "soundevents/soundevents_test.vsndevts_c" (Error: ERROR_FILEOPEN)
[ W ResourceSystem ]: Error loading resource file "particles/rain_fx/econ_weather_aurora_j.vpcf_c" (Error: ERROR_FILEOPEN)
[ W ResourceSystem ]: Error loading resource file "materials/models/heroes/blood_seeker/cape_detailmask_tga_4ec38d32.vtex_c" (Error: ERROR_FILEOPEN)
[ W ResourceSystem ]: Error loading resource file "materials/models/heroes/blood_seeker/cape_specmask_tga_7ac06b0d.vtex_c" (Error: ERROR_FILEOPEN)
[ W General        ]: ERROR: RESOURCE_TYPE_MODEL resource DBB2B0F9C3FAB7AF requested but not resident. (Missing from from a manifest?)
[ W General        ]: ERROR: RESOURCE_TYPE_MODEL resource 749F73E9F5B5BBAC requested but not resident. (Missing from from a manifest?)
[ W General        ]: ERROR: RESOURCE_TYPE_MODEL resource 9204A3A3475C5E7A requested but not resident. (Missing from from a manifest?)
[ W General        ]: ERROR: RESOURCE_TYPE_MODEL resource 3051711EB5AB0958 requested but not resident. (Missing from from a manifest?)
[ W General        ]: ERROR: RESOURCE_TYPE_MODEL resource FF9CEE873EC33CBE requested but not resident. (Missing from from a manifest?)
[ W General        ]: ERROR: RESOURCE_TYPE_MODEL resource E22DF3048623A5A2 requested but not resident. (Missing from from a manifest?)
[ W General        ]: ERROR: RESOURCE_TYPE_MODEL resource 2511A6400009D44C requested but not resident. (Missing from from a manifest?)
[ W General        ]: ERROR: RESOURCE_TYPE_MODEL resource 84393A296F502EE0 requested but not resident. (Missing from from a manifest?)
[ W General        ]: ERROR: RESOURCE_TYPE_MODEL resource 9CB2FE64F00D3D80 requested but not resident. (Missing from from a manifest?)
[ W General        ]: ERROR: RESOURCE_TYPE_MODEL resource B5FD0EA2CF2D372B requested but not resident. (Missing from from a manifest?)
[   PanoramaScript ]: [Server] Script Runtime Error: scripts/vscripts/libraries/event.lua:63: scripts/vscripts/components/boss/ai.lua:73: attempt to index local 'player' (a nil value)
[   PanoramaScript ]: 	scripts/vscripts/internal/vconsole.lua:31: in function 'error'
[   PanoramaScript ]: [Server] Script Runtime Error: scripts/vscripts/internal/eventwrapper.lua:14: scripts/vscripts/internal/vconsole.lua:57: scripts/vscripts/components/boss/ai.lua:73: attempt to index local 'player' (a nil value)
[   PanoramaScript ]: 	scripts/vscripts/internal/vconsole.lua:31: in function 'error'
[ W ResourceSystem ]: ERROR: RESOURCE_TYPE_PARTICLE_SYSTEM resource 'particles/econ/items/antimage/antimage_weapon_basher_ti5_gold/am_basher_lightning.vpcf' (63B59969A94E43E5) requested is not loaded and may have been deleted.
[ W ResourceSystem ]: ERROR: RESOURCE_TYPE_PARTICLE_SYSTEM resource 'particles/econ/items/antimage/antimage_weapon_basher_ti5_gold/antimage_manavoid_basher_cast_gold.vpcf' (FD99741438904A30) requested is not loaded and may have been deleted.
[ W ResourceSystem ]: ERROR: RESOURCE_TYPE_PARTICLE_SYSTEM resource 'particles/econ/items/antimage/antimage_weapon_basher_ti5_gold/am_basher_lightning.vpcf' (63B59969A94E43E5) requested is not loaded and may have been deleted.
[ W ResourceSystem ]: ERROR: RESOURCE_TYPE_PARTICLE_SYSTEM resource 'particles/econ/items/antimage/antimage_weapon_basher_ti5_gold/antimage_manavoid_basher_cast_gold.vpcf' (FD99741438904A30) requested is not loaded and may have been deleted.
