### ISSUE TITLE
Martys's Mail + Rot

### ISSUE THREAD

**Issue by VoidsKeeper** [AngelArenaAllstars/Bug-Reports#7]
" Just crashed a game by activating Martyr's Mail while having Rot active on Pudge . Not sure, if this has already been mentioned" by @TeRabbitSlayer#8154

He also checked that it's not just a 1 time thing.

**Comment by CrazyByDefault** [comment]
@Chronophylos You can close this too, if https://github.com/OpenAngelArena/oaa/pull/1030 get's merged

**Comment by KarmaticNeutral** [comment]
#1030 got merged.
