### ISSUE TITLE
Short game

### ISSUE THREAD

**Issue by The-Otter** [AngelArenaAllstars/Bug-Reports#70]
I'm not sure if you have fully implemented the short game option yet but if you have then I experienced a bad bug, we were playing and made it past 50 kills in the duel, the final duel didn't start and everything froze, you could still farm and kill bosses however bosses would not give cores and hero kills were not being counted as well as when you died your death timer would just freeze. But all in all I haven't seen any bugs with normal game

**Comment by Ponnyn** [comment]
This bug is the same as ''The game breaker'' somewhat. well exept the whole ''made it past 50 kills in the duel, the final duel didn't start''
