### ISSUE TITLE
Illusions and greater arcane boots gold generation

### ISSUE THREAD

**Issue by VTVTVT** [AngelArenaAllstars/Bug-Reports#73]
Any hero with illusions can buy greater arcane boots/grieves and have a lot of gold.
Monkey King an Phantom Lancer can get rich so fast nobody can keep up.

This issue breakes the game expirience sometimes. Especially when there is a party of people rushing first roshan.

**Comment by Trildar** [comment]
Fixed in OpenAngelArena/oaa@eec59b420b8f0f2a7f36a8d9e02ab239111f30ee.
