### ISSUE TITLE
Dagon lvl 2-5 and Linken's Sphere interaction

### ISSUE THREAD

**Issue by VTVTVT** [AngelArenaAllstars/Bug-Reports#75]
Linken's Sphere cant block dagon lvl 2-5. Bad when playing tinker. A lot of people get linkens and in classic dota dagon is usually the answer.

It's not a big deal, but its better to have spells work how they work in classic dota.

**Comment by Trildar** [comment]
Fixed in OpenAngelArena/oaa@c2fccfb5f5856a0ee428a9faa711c1e2f7381b1b.
