### ISSUE TITLE
"This item is not allowed for the hero" - issue

### ISSUE THREAD

**Issue by VTVTVT** [AngelArenaAllstars/Bug-Reports#76]
Breakes the game expirience for everybody. Need to constantly drop items to build new ones. When item count reaches 9-15.

Also game lags when you have 5-6 cores.

If you are playing lone druid - this issue can come up even before u have all 12 slots.

**Comment by VTVTVT** [comment]
Also game lags when unused core's count comes to 5-6

**Comment by Chronophylos** [comment]
The first issue is a Dota issue not allowing players more than a specific amount of (non consumable) items.

I haven't had any problems when I had 12 cores. This must be your PC. The cores are no different than any other item (except they're used in a lot of recipes)

And third: Yes 5-6 is less than 12

**Comment by Trildar** [comment]
Not really directly fixable. Somewhat related, are ongoing discussions to implement uses for excess cores.
