### ISSUE TITLE
Phoenix egg meets eney fountain

### ISSUE THREAD

**Issue by Wujekklawy** [AngelArenaAllstars/Bug-Reports#81]
## Event

useing Phoenix ultimate in enemy base, close enough to be affected by fountain.

## Expectation

Phoenix turns to egg -> fountain attacks egg -> egg dies -> phoenix is dead

## Result

Phoenix turns to egg -> fountain pulls him out of egg (egg still existe) -> egg is ignored, pheonix get damaged -> pheonix dies then egg with him

## Document

![20171209165559_1](https://user-images.githubusercontent.com/25621896/33797087-e6efb1a0-dd01-11e7-896f-a00fea962117.jpg)

**Comment by Trildar** [comment]
Technically a Valve bug, as the modifier that hides Phoenix is purgable, and the fountain applies a continuous purge. Mostly a visual issue anyway, as Phoenix would die regardless.
