### ISSUE TITLE
Wraith King Crit particles "X" Error

### ISSUE THREAD

**Issue by warpdragon** [AngelArenaAllstars/Bug-Reports#83]
# Event
Playing with Timo as Wraithking. Wraithking would crit as normal after skililng the crit. It was the new "Frostivus" skin as well.

# Expectation
Crit number particles

# Result
Multiple Red "X" errors everytime he got a crit. The numbers didn't show up I think

# Workarounds
None known. Possibly a different skin?

# Attachments
https://pastebin.com/2c6Kvmfb

**Comment by Trildar** [comment]
Is this still happening?
