### ISSUE TITLE
Blood Mage-Cleave Bug

### ISSUE THREAD

**Issue by Nortlen** [AngelArenaAllstars/Bug-Reports#86]
While Blood Mage is active you take damage from cleave, even though it is not affected by spell amp. Tested with Sven and Power Treads.

**Comment by Nortlen** [comment]
Also Haganeko how is it normal, that blood mage damages you when it doesn't increase your damage?
Please explain.

**Comment by imaGecko** [comment]
OpenAngelArena/oaa#1721
